### ISSUE TITLE
./phpmyadmin.sh is not executable

### ISSUE THREAD

**Issue by williamdes** [centminmod/phpmyadmin#2]
Please chmod +x the `./phpmyadmin.sh` script

**Comment by centminmod** [comment]
Thanks for that. Fixed now if you do git clones.

FYI, phpmyadmin.sh is only made for Centmin Mod LEMP stacks Nginx structure and instructions just get folks to download and chmod +x themselves at https://centminmod.com/addon_phpmyadmin.html
