### ISSUE TITLE
404 file / directory, this is fresh install from my log. phpmyadmin just showing blank page

### ISSUE THREAD

**Issue by amican** [centminmod/phpmyadmin#4]
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/themes/pmahomme/css/theme.css" failed (2: No such file or directory), cl$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/ajax.js" failed (2: No such file or directory), client: 180.244.$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/keyhandler.js" failed (2: No such file or directory), client: 18$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/name-conflict-fixes.js" failed (2: No such file or directory), c$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/menu_resizer.js" failed (2: No such file or directory), client: $
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/cross_framing_protection.js" failed (2: No such file or director$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/config.js" failed (2: No such file or directory), client: 180.24$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/doclinks.js" failed (2: No such file or directory), client: 180.$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/functions.js" failed (2: No such file or directory), client: 180$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/navigation.js" failed (2: No such file or directory), client: 18$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/indexes.js" failed (2: No such file or directory), client: 180.2$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/common.js" failed (2: No such file or directory), client: 180.24$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/page_settings.js" failed (2: No such file or directory), client:$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/codemirror/addon/lint/sql-lint.js" failed (2: No such file or di$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/error_report.js" failed (2: No such file or directory), client: $
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/drag_drop_import.js" failed (2: No such file or directory), clie$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/shortcuts_handler.js" failed (2: No such file or directory), cli$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/console.js" failed (2: No such file or directory), client: 180.2$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/ajax.js" failed (2: No such file or directory), client: 180.244.$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/keyhandler.js" failed (2: No such file or directory), client: 18$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/name-conflict-fixes.js" failed (2: No such file or directory), c$
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/menu_resizer.js" failed (2: No such file or directory), client: $
2022/07/04 12:44:26 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/cross_framing_protection.js" failed (2: No such file or director$
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/config.js" failed (2: No such file or directory), client: 180.24$
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/doclinks.js" failed (2: No such file or directory), client: 180.$
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/functions.js" failed (2: No such file or directory), client: 180$
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/navigation.js" failed (2: No such file or directory), client: 18$
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/indexes.js" failed (2: No such file or directory), client: 180.2$
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/common.js" failed (2: No such file or directory), client: 180.24$
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/page_settings.js" failed (2: No such file or directory), client:$
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/codemirror/addon/lint/sql-lint.js" failed (2: No such file or di$
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/error_report.js" failed (2: No such file or directory), client: $
2022/07/04 12:44:27 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/drag_drop_import.js" failed (2: No such file or directory), clie$
2022/07/04 12:44:28 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/shortcuts_handler.js" failed (2: No such file or directory), cli$
2022/07/04 12:44:28 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/console.js" failed (2: No such file or directory), client: 180.2$
2022/07/04 12:44:38 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/themes/pmahomme/css/theme.css" failed (2: No such file or directory), cl$
2022/07/04 12:44:38 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/ajax.js" failed (2: No such file or directory), client: 180.244.$
2022/07/04 12:44:38 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/keyhandler.js" failed (2: No such file or directory), client: 18$
2022/07/04 12:44:38 [error] 2231#2231: *37 open() "/usr/local/nginx/html/30237_mysqladmin31260/js/dist/name-conflict-fixes.js" failed (2: No such file or directory), c$

**Comment by centminmod** [comment]
Thanks for the report. I see the problem now and it's fixed in updated phpmyadmin.sh https://github.com/centminmod/phpmyadmin/commit/879606222ddb846d73fd75de9bc46d82d5bf6ac7

You can run the uninstaller `/root/tools/phpmyadmin_uninstall.sh` and re-try a fresh install with updated phpmyadmin.sh

**Comment by amican** [comment]
it worked, thx
